import 'package:cloud_firestore/cloud_firestore.dart';

class Blog {
  final String? blogID;
  final String? blogTitle;
  final String? blogDesc;
  final Timestamp? blogDate;
  final String? blogImageUrl;
  final String? writerID;
  final int? blogLikes;
  final String? blogComment;
  final String? blogShare;

  Blog({
    this.blogID,
    this.blogTitle,
    this.blogDesc,
    this.blogDate,
    this.blogImageUrl,
    this.writerID,
    this.blogLikes,
    this.blogComment,
    this.blogShare,
  });

  Map<String, dynamic> toMap() {
    return {
      "blogID": blogID,
      "blogTitle": blogTitle,
      "blogDesc": blogDesc,
      "blogDate": blogDate ?? FieldValue.serverTimestamp(),
      "blogImageUrl": blogImageUrl,
      "writerID": writerID,
      "blogLikes": blogLikes,
      "blogComment": blogComment,
      "blogShare": blogShare,
    };
  }

  Blog.fromMap(Map<String, dynamic> map)
      : blogID = map["blogID"],
        blogTitle = map["blogTitle"],
        blogDesc = map["blogDesc"],
        blogDate = map["blogDate"],
        blogImageUrl = map["blogImageUrl"],
        writerID = map["writerID"],
        blogLikes = map["blogLikes"],
        blogComment = map["blogComment"],
        blogShare = map["blogShare"];

  @override
  String toString() {
    return "Mesaj{blogID: $blogID, blogTitle: $blogTitle, blogDesc: $blogDesc, blogDate: $blogDate, blogImageUrl: $blogImageUrl, writerID: $writerID, blogLikes: $blogLikes, blogComment: $blogComment, blogShare: $blogShare}";
  }
}


/*List<Blog> allBlogs = [
  Blog(
    blogID: 1,
    blogTitle: "My Example Blog 1",
    blogDesc: desc,
    blogDate: "16.01.2022",
    blogImageUrl: "assets/images/z.jpeg",
    blogWriter: allWriters[0],
    blogLikes: 25,
    blogComment: "10",
    blogShare: "2",
    isSelect: false,
  ),
  Blog(
    blogID: 2,
    blogTitle: "My Example Blog 2",
    blogDesc: desc,
    blogDate: "26.12.2021",
    blogImageUrl: "assets/images/y3.jpeg",
    blogWriter: allWriters[1],
    blogLikes: 18,
    blogComment: "24",
    blogShare: "7",
    isSelect: false,
  ),
  Blog(
    blogID: 3,
    blogTitle: "My Example Blog 3",
    blogDesc: desc,
    blogDate: "05.01.2022",
    blogImageUrl: "assets/images/w.jpeg",
    blogWriter: allWriters[2],
    blogLikes: 75,
    blogComment: "30",
    blogShare: "30",
    isSelect: false,
  ),
  Blog(
    blogID: 4,
    blogTitle: "My Example Blog 4",
    blogDesc: desc,
    blogDate: "12.01.2021",
    blogImageUrl: "assets/images/x.jpeg",
    blogWriter: allWriters[3],
    blogLikes: 3,
    blogComment: "1",
    blogShare: "1",
    isSelect: false,
  ),
  Blog(
    blogID: 5,
    blogTitle: "My Example Blog 5",
    blogDesc: desc,
    blogDate: "20.12.2021",
    blogImageUrl: "assets/images/t.jpeg",
    blogWriter: allWriters[4],
    blogLikes: 5,
    blogComment: "2",
    blogShare: "3",
    isSelect: false,
  ),
  Blog(
    blogID: 6,
    blogTitle: "My Example Blog 6",
    blogDesc: desc,
    blogDate: "16.05.2021",
    blogImageUrl: "assets/images/s5.jpeg",
    blogWriter: allWriters[5],
    blogLikes: 13,
    blogComment: "10",
    blogShare: "5",
    isSelect: false,
  ),
  Blog(
    blogID: 7,
    blogTitle: "My Example Blog 7",
    blogDesc: desc,
    blogDate: "08.05.2021",
    blogImageUrl: "assets/images/s3.jpeg",
    blogWriter: allWriters[6],
    blogLikes: 32,
    blogComment: "11",
    blogShare: "10",
    isSelect: false,
  ),
  Blog(
    blogID: 8,
    blogTitle: "My Example Blog 8",
    blogDesc: desc,
    blogDate: "06.04.2021",
    blogImageUrl: "assets/images/s2.jpeg",
    blogWriter: allWriters[7],
    blogLikes: 18,
    blogComment: "5",
    blogShare: "2",
    isSelect: false,
  ),
  Blog(
    blogID: 9,
    blogTitle: "My Example Blog 9",
    blogDesc: desc,
    blogDate: "15.01.2022",
    blogImageUrl: "assets/images/s1.jpeg",
    blogWriter: allWriters[0],
    blogLikes: 39,
    blogComment: "14",
    blogShare: "11",
    isSelect: false,
  ),
  Blog(
    blogID: 16,
    blogTitle: "My Example Blog 16",
    blogDesc: desc,
    blogDate: "11.11.2021",
    blogImageUrl: "assets/images/r5.jpeg",
    blogWriter: allWriters[1],
    blogLikes: 30,
    blogComment: "17",
    blogShare: "5",
    isSelect: true,
  ),
];

List<Blog> popularBlogs = [
  Blog(
    blogID: 1,
    blogTitle: "My Example Blog 1",
    blogDesc: desc,
    blogDate: "16.01.2022",
    blogImageUrl: "assets/images/img1.jpeg",
    blogWriter: allWriters[2],
    blogLikes: 25,
    blogComment: "10",
    blogShare: "2",
    isSelect: false,
  ),
  Blog(
    blogID: 16,
    blogTitle: "My Example Blog 16",
    blogDesc: desc,
    blogDate: "11.11.2021",
    blogImageUrl: "assets/images/img3.jpeg",
    blogWriter: allWriters[3],
    blogLikes: 30,
    blogComment: "17",
    blogShare: "5",
    isSelect: true,
  ),
  Blog(
    blogID: 17,
    blogTitle: "My Example Blog 17",
    blogDesc: desc,
    blogDate: "16.09.2021",
    blogImageUrl: "assets/images/img2.jpeg",
    blogWriter: allWriters[4],
    blogLikes: 12,
    blogComment: "16",
    blogShare: "1",
    isSelect: true,
  ),
  Blog(
    blogID: 3,
    blogTitle: "My Example Blog 3",
    blogDesc: desc,
    blogDate: "05.01.2022",
    blogImageUrl: "assets/images/c.jpeg",
    blogWriter: allWriters[5],
    blogLikes: 75,
    blogComment: "30",
    blogShare: "30",
    isSelect: false,
  ),
  Blog(
    blogID: 9,
    blogTitle: "My Example Blog 9",
    blogDesc: desc,
    blogDate: "15.01.2022",
    blogImageUrl: "assets/images/a3.jpeg",
    blogWriter: allWriters[6],
    blogLikes: 39,
    blogComment: "14",
    blogShare: "11",
    isSelect: false,
  ),
  Blog(
    blogID: 15,
    blogTitle: "My Example Blog 15",
    blogDesc: desc,
    blogDate: "18.02.2021",
    blogImageUrl: "assets/images/y.jpeg",
    blogWriter: allWriters[7],
    blogLikes: 26,
    blogComment: "12",
    blogShare: "8",
    isSelect: false,
  ),
];

List<Blog> lastBlogs = [
  Blog(
    blogID: 6,
    blogTitle: "My Example Blog 6",
    blogDesc: desc,
    blogDate: "16.12.2022",
    blogImageUrl: "assets/images/h.jpeg",
    blogWriter: allWriters[0],
    blogLikes: 13,
    blogComment: "10",
    blogShare: "4",
    isSelect: false,
  ),
  Blog(
    blogID: 9,
    blogTitle: "My Example Blog 9",
    blogDesc: desc,
    blogDate: "15.01.2022",
    blogImageUrl: "assets/images/q.jpeg",
    blogWriter: allWriters[1],
    blogLikes: 80,
    blogComment: "25",
    blogShare: "12",
    isSelect: true,
  ),
  Blog(
    blogID: 12,
    blogTitle: "My Example Blog 12",
    blogDesc: desc,
    blogDate: "30.01.2022",
    blogImageUrl: "assets/images/k.jpeg",
    blogWriter: allWriters[2],
    blogLikes: 12,
    blogComment: "4",
    blogShare: "5",
    isSelect: false,
  ),
  Blog(
    blogID: 4,
    blogTitle: "My Example Blog 4",
    blogDesc: desc,
    blogDate: "06.02.2022",
    blogImageUrl: "assets/images/e.jpeg",
    blogWriter: allWriters[3],
    blogLikes: 90,
    blogComment: "34",
    blogShare: "20",
    isSelect: true,
  ),
];*/
